name: 'stackt'
version: '1.0.0'
config-version: 2

profile: 'stackt_user'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  stackt:
    # Config indicated by + and applies to all files under models/example/

    staging:
      +schema: staging
      +materialized: table

    transform:
      +schema: stackt
      +materialized: table

    intermediate:
      +schema: intermediate
      +materialized: table

    graph:
      +schema: graph
      +materialized: table

    mart:
      +schema: mart
      +materialized: table
